### ISSUE TITLE
Image update and readme refactoring

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/tool-generic_filter#2]
Old style can be nice for clothes but this tool needs a restyling. 
To do:
- [x] Image update
- [x] Readme in Markdown

**Comment by lecorguille** [comment]
I'm currently working on the pictures with [yED](https://www.yworks.com/products/yed)
By tomorrow, I will be able to show you something

**Comment by melpetera** [comment]
I made a picture inspired by your yED picture.
#3

**Comment by lecorguille** [comment]
Why don't you use the pallette for the tool and the noodle?
Otherwise, it's cool :)

**Comment by melpetera** [comment]
Well, I made the picture by modifying the BigPic you made. I opened the palette also to check but it seemed that it was the same as what was used in the BigPic any way. Did I miss something? (obviously yes but what?)

**Comment by melpetera** [comment]
I wanted to remake the picture all right this week but I can not find time. I will valid #3 for now to have at least module names updated before prod deadline.
I will prepare the right picture for next prod big update for sure!

**Comment by lecorguille** [comment]
No problemo

**Comment by melpetera** [comment]
New version in [#20](https://github.com/workflow4metabolomics/workflow4metabolomics/pull/20) from the global picture repository

**Comment by melpetera** [comment]
So old. Done in 6e943b5
